Add tests
savaukr/matrixSSRnew pull request #2
Opened 2021-06-01 14:29 UTC by savaukr

2021-06-01 14:41 UTC, max-mykhailenko requested changes

2021-06-01 14:41 UTC, max-mykhailenko commented on package.json
> +    "test": "jest --env=jsdom",
Нужно чтобы код работал и в среде ноды и в среде браузера. За что отвечает env?

2021-06-01 14:41 UTC, max-mykhailenko commented on setUpTests.js
> +import mmm from '@testing-library/jest-dom/extend-expect';
@testing-library зачем тебе нужна эта либа?

2021-06-01 14:41 UTC, max-mykhailenko commented on src/App.test.tsx
> +    });
Необходимо добавить рендеринг в снепшот, тогда провериться не только одна кнопка, а в принципе все

2021-06-01 14:41 UTC, max-mykhailenko commented on src/App.test.tsx
> +        expect(h4.props.children).toEqual(["Matrix ", 1, "x", 3])
Необходимо добавить рендеринг в снепшот, тогда провериться не только одна кнопка, а в принципе все

2021-06-01 14:41 UTC, max-mykhailenko commented on src/App.test.tsx
> +        preloadedState = {
Это состояние можно вынести выше в константу и использовать по надобности в разных тестах

2021-06-01 14:41 UTC, max-mykhailenko commented on src/App.test.tsx
> +        document.body.removeChild(container);
Вот это странная строка, она точно нужна?

2021-06-01 14:41 UTC, max-mykhailenko commented on src/App.test.tsx
> +        act(() => expect(+ceil.props.children[0]).toEqual(amount+1))
Нужно сравнивать не html, а снепшоты и состояние редакса

2021-06-01 14:41 UTC, max-mykhailenko commented on src/App.test.tsx
> +        actUtils(renderComponent);
ты можешь выбрать тот act, который подходит и использовать только его, они на сколько я помню взаимозаменяемые

2021-06-01 14:41 UTC, max-mykhailenko commented on src/App.test.tsx
> +        ReactTestUtils.Simulate.click(ceilDom)
нормас

2021-06-01 14:41 UTC, max-mykhailenko commented on src/App.test.tsx
> +    });
По всем тестам выше замечания такие же как уже дал

2021-06-03 09:25 UTC, savaukr commented on src/App.test.tsx
> +        act(() => expect(+ceil.props.children[0]).toEqual(amount+1))
виправив

2021-06-03 09:26 UTC, max-mykhailenko approved these changes
Это красивые изменения, этот ПР закрывай, для новых тестов создашь новый

2021-06-03 09:28 UTC, savaukr commented on src/App.test.tsx
> +        document.body.removeChild(container);
раз ти так кажеш, то напевне непотрібна. Видалив і виніс з beforeEach : container = document.createElement("div");

2021-06-03 09:28 UTC, savaukr commented on src/App.test.tsx
> +        preloadedState = {
зробив так

2021-06-03 09:28 UTC, savaukr commented on src/App.test.tsx
> +        expect(h4.props.children).toEqual(["Matrix ", 1, "x", 3])
добавив снепшоти

2021-06-03 09:29 UTC, savaukr commented on src/App.test.tsx
> +    });
добавив снепшот, об'єднав в идин тест

2021-06-03 09:35 UTC, merged